#spring:
#  application.name: flowable
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://127.0.0.1:3306/flowable?characterEncoding=UTF-8
#
#logging:
#  level:
#    root: error
#    cn: debug
#    standalone: debug
