spring:
  datasource:
    druid:
      main:
        url:  jdbc:mysql://localhost:3306/main?characterEncoding=UTF-8
        username: root
        password: root
      flowable:
        url:  jdbc:mysql://localhost:3306/flowable?characterEncoding=UTF-8
        username: root
        password: root